# Project information
site_name: Friends of Toowong Cemetery
site_url: https://stephen-gates.github.io/fotc/
site_author: Friends of Toowong Cemetery Association Incorporated
site_description: >-
  Friends of Toowong Cemetery is a volunteer group that discover and share the history and stories of Toowong Cemetery.
copyright: © 1996 — 2021 Friends of Toowong Cemetery Association Incorporated. 
# repo_url: https://github.com/Stephen-Gates/fotc
# repo_name: Stephen-Gates/fotc
# edit_uri: ""

# Configuration
theme:
  language: en
  name: material
  logo: assets/fotc-logo.png
  favicon: assets/favicon.ico
#  icon:
#    repo: fontawesome/brands/github-alt
  font:
    text: Raleway
    code: Roboto Mono 
  palette:
  - scheme: default
    primary: deep-purple
    accent: purple
#    toggle:
#      icon: octicons/sun-16
#      name: Switch to light mode
#  - scheme: slate
#    primary: purple
#    accent: purple
#    toggle:
#      icon: octicons/moon-16
#      name: Switch to dark mode
  icon:
    admonition:
      question: fontawesome/solid/hand-holding-heart
      example: fontawesome/regular/compass
      warning: fontawesome/regular/check-circle
#      tip: fontawesome/regular/question-circle
  custom_dir: overrides
  features:
#    - announce.dismiss
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - search.highlight
    - search.suggest

# Customization
extra:
  generator: false
  social:
    - icon: fontawesome/solid/phone
      link: tel:0439998053
      name: Call us on the phone 0439998053
    - icon: fontawesome/solid/envelope
      link: mailto:inquiries@fotc.org.au
      name: Send us an email      
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/1871fotc/
      name: We're also on facebook
#    - icon: fontawesome/solid/thumbs-down
    - icon: material/heart-broken
      link: https://docs.google.com/forms/d/e/1FAIpQLSeS7K7-e-ofnn2OkPDL6ql7-CkBL67wwsQiv9upMDoRcXCRJQ/viewform?usp=pp_url&entry.975252590= 
      name: Provide feedback
#    - icon: fontawesome/brands/creative-commons
#      link: https://creativecommons.org/licenses/by/4.0/
#      name: CC-BY 4.0 licence
#  analytics: 
#    provider: google
#    property: G-FT5X64207N
#    feedback:
#      title: Was this page helpful?
#      ratings:
#        - icon: material/emoticon-happy-outline
#          name: This page was helpful
#          data: 1
#          note: >-
#            Thanks for your feedback!
#        - icon: material/emoticon-sad-outline
#          name: This page could be improved
#          data: 0
#          note: >-
#            Thanks! Help us improve this page by
#            completing our <a href="https://docs.google.com/forms/d/e/1FAIpQLSeS7K7-e-ofnn2OkPDL6ql7-CkBL67wwsQiv9upMDoRcXCRJQ/viewform?usp=pp_url&entry.975252590={}" target=_blank>feedback form</a>.
#
# See https://support.google.com/a/users/answer/9308781?hl=en; add {} to URL answer; copy link; replace =%7B%7D with ={}; done            
# https://docs.google.com/forms/d/e/1FAIpQLSeS7K7-e-ofnn2OkPDL6ql7-CkBL67wwsQiv9upMDoRcXCRJQ/viewform?usp=pp_url&entry.975252590=%7B%7D
#
#  consent:
#    title: Cookie consent
#    description: >-
#      <p>We use cookies to recognise your repeated visits, determine if you find what you're searching for, and measure if you think this site is helpful.</p>
#      <p>With your consent, you're helping us to make this site better.</p>
  
extra_css:
  - stylesheets/extra.css

# Extensions  
markdown_extensions:
  - toc:
      title: On this page
      toc_depth: 2
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde   
  - pymdownx.snippets

# Sortable data table
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
  
# Plugins
plugins:
  - search
#  - social:
#      cards_directory: assets/images/social
#      cards_color:
#        fill: "#7e56c2" 
#        text: "#FFFFFF"

# Page tree - only 2 levels allowed
# order walks better
nav:
  - Home: index.md
  - Toowong Cemetery: 
    - Discover Toowong Cemetery: cemetery/discover.md
    - History: cemetery/history.md
    - Museum: cemetery/museum.md 
    - Finding Graves: cemetery/finding-graves.md
  - Guided Tours: guided-tours.md
  - Self-Guided Walks:
    - Self-Guided Walks: walks/index.md
    - The Federation Trail: walks/federation-trail.md
    - Governors: walks/governors-past.md 
    - Brisbane Mayors: walks/brisbane-mayors.md
    - Labor Luminaries: walks/labor-luminaries.md
    - Colonial Conflicts: walks/colonial-conflicts.md         
    - Lest We Forget: walks/lest-we-forget.md
    - Lest We Forget - Naval: walks/lest-we-forget-navy.md 
#    - Toowong Cemetery Remembrance Walk: walks/rememberance-walk.md 
    - Men of the Royal Navy: walks/men-of-the-royal-navy.md
    - Scots in the AIF: walks/scots-in-the-aif-ww1.md
    - Artists: walks/artists.md 
#    - Health Professionals: walks/in-their-caring-hands.md
#    - Judiciary: walks/early-judiciary.md
    - Mariners: walks/anchors-aweigh.md
    - Performers: walks/all-the-worlds-a-stage.md 
    - Police: walks/thin-blue-line.md 
    - Print Media Identities: walks/printers.md
    - Sporting Personalities: walks/sporting-personalities.md
    - Undertakers: walks/undertakers-underground.md
    - Founding Fathers: walks/founding-fathers.md     
    - Notable Women: walks/notable-women.md    
    - Toowong Identities 1: walks/toowong-identities-1.md 
    - Toowong Identities 2: walks/toowong-identities-2.md 
    - Children: walks/children.md 
    - Convicts: walks/convict-connections.md 
    - The Irish: walks/irish-trail.md 
#    - The Jewish Trail: walks/jewish-trail.md    
    - The Lutheran: walks/lutheran-trail.md    
#    - BCC Toowong Cemetery Tour 1: walks/bcc-walk-1.md 
#    - BCC Toowong Cemetery Tour 2: walks/bcc-walk-2.md 
  - Headstones: 
    - Symbols: headstones/index.md
#    - Shapes: headstones/shapes.md  
    - Signs: headstones/signs.md  
    - Archaeological Digs: headstones/archaeological-digs.md
#    - Celebrity Headstones: headstones/celebrities.md
#    - History Mystery: headstones/mystery.md
  - Biographies: 
    - Biography Index: bios/bio-index.md
    - Research Resources: bios/research.md
  - Events: 
#  - News and Events:
#    - News: news/index.md
    - Upcoming Events: news/index.md
#    - Past News: news/past-news.md 
    - Past Events: news/past-events.md
  - About Us: 
    - About Friends of Toowong Cemetery: about/index.md
    - Federation Pavilion: about/federation-pavilion.md
    - 140th Anniversary Commemoration: about/140-commemoration.md
    - Legal: about/legal.md
#    - Ideas: about/ideas.md
