site_name: Friends of Toowong Cementery
copyright: Copyright &copy; 2021 Friends of Toowong Cemetery, unless otherwise noted. 

theme:
  name: material
  custom_dir: overrides
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.top
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.indexes
  - search.highlight
  - search.suggest
  - search.share

extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/1871fotc/
      name: We're also on facebook 
    - icon: fontawesome/solid/envelope
      link: mailto:inquiries@fotc.org.au
      name: Send us an email
#    - icon: fontawesome/brands/creative-commons
#      link: https://creativecommons.org/licenses/by/4.0/
#      name: CC-BY 4.0 licence
  
extra_css:
  - stylesheets/extra.css
  
markdown_extensions:
  - toc:
      title: On this page
      toc_depth: 2
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde   
  

# Page tree - only 2 levels allowed
nav:
  - Home: index.md
  - The Cemetery: cemetery.md
  - Guided Heritage Walks: guided-walks.md
  - Self-Guided Walks:
    - Self-Guided Walks: walks/index.md
    - BCC Toowong Cemetery self-guided walk one: walks/bcc-walk-1.md 
    - Undertakers Underground: walks/bcc-walk-1.md  
    - Colonial Conflicts: walks/bcc-walk-1.md 
    - The Thin Blue Line - Queensland Colonial Policing: walks/bcc-walk-1.md 
    - Lest we forget - Navy Walk: walks/bcc-walk-1.md 
    - The Federation Trail: walks/bcc-walk-1.md  
    - Governors Past: walks/bcc-walk-1.md  
    - The Irish Trail: walks/bcc-walk-1.md 
    - The Jewish Trail: walks/bcc-walk-1.md 
    - Toowong Identities Tour Course A: walks/bcc-walk-1.md 
    - Toowong Identities Tour Course B: walks/bcc-walk-1.md 
    - In their caring hands - A heritage trail to commemorate the role of nurses, doctors and health professionals: walks/bcc-walk-1.md 
    - Lest We Forget: walks/bcc-walk-1.md 
    - Anchors Aweigh! A Maritime Walk through Toowong Cemetery: walks/bcc-walk-1.md 
    - Notable Women: walks/bcc-walk-1.md 
    - Suffer the children to come unto me: walks/bcc-walk-1.md 
    - Founding Fathers - Members of the first Brisbane General Cemetery Trust: walks/bcc-walk-1.md 
    - Brisbane Mayors: walks/bcc-walk-1.md 
    - Labor Luminaries: walks/bcc-walk-1.md 
    - With all the company of heaven - A Lutheran Heritage Trail: walks/bcc-walk-1.md 
    - Convict Connections: walks/bcc-walk-1.md 
    - All the world’s a stage: walks/bcc-walk-1.md 
    - Artists: walks/bcc-walk-1.md 
  - Biographies: biographies.md
  - About Us: 
    - About Us: about/index.md
    - 140th Anniversary Commemoration: about/140-commemoration.md
