# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Project information
site_name: Friends of Toowong Cemetery
site_url: https://1871fotc.github.io/fotc/
site_author: Friends of Toowong Cemetery Association Inc.
site_description: >-
  Friends of Toowong Cemetery is a volunteer group that discover and share the history and stories of Toowong Cemetery.
copyright: © 1992 — 2022 Friends of Toowong Cemetery Association Inc., unless noted otherwise. 
# repo_url: https://github.com/1871fotc/fotc
# repo_name: 1871fotc/fotc
# edit_uri: ""

# Configuration
theme:
  language: en
  name: material
  logo: assets/fotc-logo.png
  favicon: assets/favicon.ico
  font:
    text: Raleway
    code: Roboto Mono 
  palette:
    scheme: default
    primary: deep-purple
    accent: purple
# toggle between alternate schemes
#    - scheme: default
#      primary: deep-purple
#      accent: purple
#      toggle:
#        icon: octicons/sun-16
#        name: Switch to dark mode
#    - scheme: slate
#      primary: purple
#      accent: purple
#      toggle:
#        icon: custom/ghost
#        name: Switch to light mode
  icon:
    admonition:
      question: fontawesome/solid/hand-holding-heart
      example: fontawesome/regular/compass
  custom_dir: overrides
  features:
# instant and announce seem to conflict with was this page helpful. Pick one. Works on Material for Mkdocs - look there. 
#    - announce.dismiss
#    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - search.highlight
    - search.suggest
    - content.code.annotate
    - toc.follow

# Customization
extra:
  generator: false
  social:
#    - icon: fontawesome/solid/phone
#      link: tel:0439998053
#      name: Call us on 0439998053
    - icon: fontawesome/solid/envelope
      link: mailto:stephen.gates@me.com
      name: Email us
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/1871fotc/
      name: Facebook @1871fotc
    - icon: fontawesome/brands/github
      link: https://github.com/1871fotc
      name: Code, data and more on GitHub
# Add twitter when Social Cards are working https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/?h=soci
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/1871fotc
#      name: Twitter @1871fotc
# Used for feedback to avoid clash with announce dismiss
#    - icon: material/heart-broken
#      link: https://docs.google.com/forms/d/e/1FAIpQLSeS7K7-e-ofnn2OkPDL6ql7-CkBL67wwsQiv9upMDoRcXCRJQ/viewform?usp=pp_url&entry.975252590= 
#      name: Provide feedback
  analytics: 
    provider: google
    property: G-XDRM6G59W8
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
# Add feedback form for positive feedback
#          note: >-
#            Thanks for your feedback!<br><b><a href="https://docs.google.com/forms/d/e/1FAIpQLSeS7K7-e-ofnn2OkPDL6ql7-CkBL67wwsQiv9upMDoRcXCRJQ/viewform?usp=pp_url&entry.975252590={}" target=_blank>What did we get right?</a></b>
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! <br><b><a href="https://docs.google.com/forms/d/e/1FAIpQLSeS7K7-e-ofnn2OkPDL6ql7-CkBL67wwsQiv9upMDoRcXCRJQ/viewform?usp=pp_url&entry.975252590={}" target=_blank>How we can improve?</a></b>
#
# See https://support.google.com/a/users/answer/9308781?hl=en; add {} to URL answer; copy link; replace =%7B%7D with ={}; done            
# https://docs.google.com/forms/d/e/1FAIpQLSeS7K7-e-ofnn2OkPDL6ql7-CkBL67wwsQiv9upMDoRcXCRJQ/viewform?usp=pp_url&entry.975252590=%7B%7D
#
#  consent:
#    title: Cookie consent
#    description: >-
#      <p>We use cookies to recognise your repeated visits, determine if you find what you're searching for, and measure if you think this site is helpful.</p>
#      <p>With your consent, you're helping us make this site better.</p>
  
extra_css:
  - stylesheets/extra.css

# Extensions  
markdown_extensions:
  - toc:
      title: On this page
      toc_depth: 2
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
# custom icon - ghost in dark mode      
#      options:
#        custom_icons:
#          - overrides/.icons
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde   
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - meta

# Sortable data table
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
  
# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        'home/home.md': 'index.md'
        'home/index.md': 'index.md'
# set up redirects for deep links
        'walks/walks.md': 'walks/index.md'
        'activities/activities.md': 'about/index.md'
        'obituaries/obituaries.md': 'story/index.md'
        'publications/publications.md': 'about/publications.md'
        'membership/membership.md': 'about/index.md'
        'links/links.md': 'story/research.md'
        'contactus/contactus.md': 'about/index.md'
  - privacy:
      externals: bundle
#
# comment out for local builds as cannot resolve missing dependencies
  - social

# Page tree - only 2 levels allowed
nav:
  - Home: index.md
  - Toowong Cemetery: 
    - Visit: cemetery/visit.md
    - History: cemetery/history.md
    - Museum: cemetery/museum.md 
    - Finding Graves: cemetery/finding-graves.md
  - Guided Tours: guided-tours.md
  - Self-Guided Walks:
    - Self-Guided Walks: walks/index.md
# Politics    
    - The Federation Trail: walks/federation-trail.md
    - Governors: walks/governors-past.md 
    - Brisbane Mayors: walks/brisbane-mayors.md
    - Labor Luminaries: walks/labor-luminaries.md
    - One Adult, One Vote: walks/suffrage.md
    - The Great Shearers' Strike of 1891: walks/shearers-strike.md
# Military
    - Colonial Conflicts: walks/colonial-conflicts.md         
    - Lest We Forget: walks/lest-we-forget.md
    - Lest We Forget - Naval: walks/lest-we-forget-navy.md 
#    - Toowong Cemetery Remembrance Walk: walks/rememberance-walk.md 
    - Men of the Royal Navy: walks/men-of-the-royal-navy.md
    - Scots in the AIF: walks/scots-in-the-aif-ww1.md
    - 1919 Soldiers: walks/1919-soldiers.md
    - Conflict and Compassion: walks/conflict-and-compassion.md
# Professions    
    - Artists: walks/artists.md 
    - Health Professionals: walks/in-their-caring-hands.md
    - Judiciary: walks/judiciary.md
    - Mariners: walks/anchors-aweigh.md
    - Performers: walks/all-the-worlds-a-stage.md 
    - Police: walks/thin-blue-line.md 
    - Print Media Identities: walks/printers.md
    - More Print Media Identities: walks/printers-2.md
    - Sporting Personalities: walks/sporting-personalities.md
    - Undertakers: walks/undertakers.md
# Local Identities    
    - Founding Fathers: walks/founding-fathers.md     
    - Notable Women: walks/notable-women.md    
    - Toowong Identities: walks/toowong-identities-1.md 
    - More Toowong Identities: walks/toowong-identities-2.md 
# Birds of a feather    
    - Children: walks/children.md 
    - Convicts: walks/convict-connections.md 
    - The Irish: walks/irish-trail.md 
    - The Jewish: walks/jewish-trail.md    
    - The Lutheran: walks/lutheran-trail.md
# Other walks     
    - 20/20 Vision: walks/2020-vision.md
#    - BCC Toowong Cemetery Tour 1: walks/bcc-walk-1.md 
#    - BCC Toowong Cemetery Tour 2: walks/bcc-walk-2.md 
    - Building Brisbane: walks/brisbane-open-house.md 
    - Erected by Friends and Family: walks/erected-by-friends.md    
    - Christmas: walks/christmas.md    
#    - New Year's Day: walks/new-years.md   
    - Weather: walks/weather.md 
    - Mothers: walks/mothers.md
    - Rich man, Poor man: walks/rich-man-poor-man.md
    - Prospectors: walks/prospectors.md    
    - Steam: walks/steam.md    
    - Taken before their time: walks/taken-before-their-time.md    
# portion walks
    - Portion 5 - part 1: walks/portion5-part1.md
    - Portion 5 - part 2: walks/portion5-part2.md
    - Portion 6 and 24: walks/portion6-and-24.md
    - Portion 15 and 16: walks/portion15-and-16.md
  - Headstones: 
    - Headstones: headstones/index.md
    - Signs: headstones/signs.md 
#    - Shapes: headstones/shapes.md  
#    - Monuments: headstones/monuments.md 
    - Archaeological Digs: headstones/archaeological-digs.md
#    - Celebrity Headstones: headstones/celebrities.md
  - Stories: 
    - Story Index: story/index.md
#    - Colonel Samuel Wensley Blackall: assets/guides/samuel-blackall.pdf
    - Extraordinary Stories of Ordinary People: story/extraordinary-stories.md 
#    - Our Publications: story/publications.md  link to blackall pdf converted to web page
    - Research Resources: story/research.md
  - About Us: 
    - About Us: about/index.md
    - Federation Pavilion: about/federation-pavilion.md
    - 140th Anniversary Commemoration: about/140-commemoration.md
    - Our Publications: about/publications.md
    - Data: about/data.md
    - Legal: about/legal.md
  - Contact Us: contact.md
