# Project information
site_name: Friends of Toowong Cemetery
site_url: https://stephen-gates.github.io/fotc/
site_author: Friends of Toowong Cemetery Association Incorporated
site_description: >-
  Friends of Toowong Cemetery is a volunteer group that discover and share the history and stories of Toowong Cemetery.
copyright: © 1992 — 2022 Friends of Toowong Cemetery Association Incorporated. 
# repo_url: https://github.com/Stephen-Gates/fotc
# repo_name: Stephen-Gates/fotc
# edit_uri: ""

# Configuration
theme:
  language: en
  name: material
  logo: assets/fotc-logo.png
  favicon: assets/favicon.ico
  font:
    text: Raleway
    code: Roboto Mono 
  palette:
    - scheme: default
      primary: deep-purple
      accent: purple
      toggle:
        icon: octicons/sun-16
        name: Switch to dark mode
#    - scheme: ghost
    - scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: custom/ghost
        name: Switch to light mode
  icon:
    admonition:
      question: fontawesome/solid/hand-holding-heart
      example: fontawesome/regular/compass
      warning: fontawesome/solid/exclamation-triangle
  custom_dir: overrides
  features:
 #   - announce.dismiss
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - search.highlight
    - search.suggest
    - content.code.annotate

# Customization
extra:
  generator: false
  social:
    - icon: fontawesome/solid/phone
      link: tel:0439998053
      name: Call us on 0439998053
    - icon: fontawesome/solid/envelope
      link: mailto:inquiries@fotc.org.au
      name: Email us
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/1871fotc/
      name: Facebook @1871fotc
# Add twitter when Social Cards are working https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/?h=soci
#    - icon: fontawesome/brands/twitter
#      link: https://twitter.com/1871fotc
#      name: Twitter @1871fotc
#    - icon: fontawesome/solid/thumbs-down
    - icon: material/heart-broken
      link: https://docs.google.com/forms/d/e/1FAIpQLSeS7K7-e-ofnn2OkPDL6ql7-CkBL67wwsQiv9upMDoRcXCRJQ/viewform?usp=pp_url&entry.975252590= 
      name: Provide feedback
  analytics: 
    provider: google
    property: G-FT5X64207N
#    feedback:
#      title: Was this page helpful?
#      ratings:
#        - icon: material/emoticon-happy-outline
#          name: This page was helpful
#          data: 1
#          note: >-
#            Thanks for your feedback!
#        - icon: material/emoticon-sad-outline
#          name: This page could be improved
#          data: 0
#          note: >-
#            Thanks! Help us improve this page by
#            completing our <a href="https://docs.google.com/forms/d/e/1FAIpQLSeS7K7-e-ofnn2OkPDL6ql7-CkBL67wwsQiv9upMDoRcXCRJQ/viewform?usp=pp_url&entry.975252590={}" target=_blank>feedback form</a>.
#
# See https://support.google.com/a/users/answer/9308781?hl=en; add {} to URL answer; copy link; replace =%7B%7D with ={}; done            
# https://docs.google.com/forms/d/e/1FAIpQLSeS7K7-e-ofnn2OkPDL6ql7-CkBL67wwsQiv9upMDoRcXCRJQ/viewform?usp=pp_url&entry.975252590=%7B%7D
#
  consent:
    title: Cookie consent
    description: >-
      <p>We use cookies to recognise your repeated visits, determine if you find what you're searching for, and measure if you think this site is helpful.</p>
      <p>With your consent, you're helping us to make this site better.</p>
  
extra_css:
  - stylesheets/extra.css

# Extensions  
markdown_extensions:
  - toc:
      title: On this page
      toc_depth: 2
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde   
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - meta


# Sortable data table
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js
  
# Plugins
plugins:
  - search
#  - social
#      cards_font: Raleway
#      cards_directory: assets/images/social
#      cards_color:
#        fill: "#7e56c2" 
#        text: "#FFFFFF"

# Page tree - only 2 levels allowed
# order walks better
nav:
  - Home: index.md
  - Toowong Cemetery: 
    - Visit Toowong Cemetery: cemetery/visit.md
    - History: cemetery/history.md
    - Museum: cemetery/museum.md 
    - Finding Graves: cemetery/finding-graves.md
  - Guided Tours: guided-tours.md
  - Self-Guided Walks:
    - Self-Guided Walks: walks/index.md
# Politics    
    - The Federation Trail: walks/federation-trail.md
    - Governors: walks/governors-past.md 
    - Brisbane Mayors: walks/brisbane-mayors.md
    - Labor Luminaries: walks/labor-luminaries.md
    - One Adult, One Vote: walks/suffrage.md
# Military
    - Colonial Conflicts: walks/colonial-conflicts.md         
    - Lest We Forget: walks/lest-we-forget.md
    - Lest We Forget - Naval: walks/lest-we-forget-navy.md 
#    - Toowong Cemetery Remembrance Walk: walks/rememberance-walk.md 
    - Men of the Royal Navy: walks/men-of-the-royal-navy.md
    - Scots in the AIF: walks/scots-in-the-aif-ww1.md
    - 1919 Soldiers: walks/1919-soldiers.md
    - Conflict and Compassion: walks/conflict-and-compassion.md
# Professions    
    - Artists: walks/artists.md 
    - Health Professionals: walks/in-their-caring-hands.md
    - Judiciary: walks/judiciary.md
    - Mariners: walks/anchors-aweigh.md
    - Performers: walks/all-the-worlds-a-stage.md 
    - Police: walks/thin-blue-line.md 
    - Print Media Identities: walks/printers.md
    - Sporting Personalities: walks/sporting-personalities.md
    - Undertakers: walks/undertakers.md
# Local Identities    
    - Founding Fathers: walks/founding-fathers.md     
    - Notable Women: walks/notable-women.md    
    - Toowong Identities 1: walks/toowong-identities-1.md 
    - Toowong Identities 2: walks/toowong-identities-2.md 
# Birds of a feather    
    - Children: walks/children.md 
    - Convicts: walks/convict-connections.md 
    - The Irish: walks/irish-trail.md 
    - The Jewish: walks/jewish-trail.md    
    - The Lutheran: walks/lutheran-trail.md
# Other walks     
    - 20/20 Vision: walks/2020-vision.md
#    - BCC Toowong Cemetery Tour 1: walks/bcc-walk-1.md 
#    - BCC Toowong Cemetery Tour 2: walks/bcc-walk-2.md 
    - Building Brisbane: walks/brisbane-open-house.md 
    - Erected by Friends and Family: walks/erected-by-friends.md    
    - Christmas: walks/christmas.md    
#    - New Year's Day: walks/new-years.md    
    - Mothers: walks/mothers.md  
    - Rich man, Poor man: walks/rich-man-poor-man.md
    - Prospectors: walks/prospectors.md    
    - Steam: walks/steam.md    
    - Taken before their time: walks/taken-before-their-time.md    
# portion walks
    - Portion 5 - part 1: walks/portion5-part1.md
    - Portion 5 - part 2: walks/portion5-part2.md
    - Portion 6 and 24: walks/portion6-and-24.md
    - Portion 15 and 16: walks/portion15-and-16.md
  - Headstones: 
    - Headstones: headstones/index.md
    - Signs: headstones/signs.md 
#    - Shapes: headstones/shapes.md  
    - Archaeological Digs: headstones/archaeological-digs.md
#    - Celebrity Headstones: headstones/celebrities.md
  - Biographies: 
    - Biography Index: bios/index.md
    - Research Resources: bios/research.md
#  - Events: 
#  - News and Events:
#    - News: news/index.md
#    - Upcoming Events: news/index.md
#    - Past News: news/past-news.md 
#    - Past Events: news/past-events.md
  - About Us: 
    - About Us: about/index.md
    - Federation Pavilion: about/federation-pavilion.md
    - 140th Anniversary Commemoration: about/140-commemoration.md
    - Publications: about/publications.md
    - Extraordinary Stories of Ordinary People: about/extraordinary-stories.md
    - Data: about/data.md
    - Terminology: about/terms.md
    - Legal: about/legal.md
#    - Ideas: about/ideas.md
